### ISSUE TITLE
When i upload pbf file and gtfs i receive 404 not found. 

### ISSUE THREAD

**Issue by changtung** [javandres/conveyal-analysis-docker#2]
I receive in browser 404 not found. 
In server logs there is: 
`r5          | 2023-06-30 16:49:14,218 [qtp1888567697-21] INFO  s.h.m.MatcherFilter - The requested route [/api/project/649f00f2d40a3d001f040ccf/modifications] has not been mapped in Spark for Accept: [*/*]
r5          | 2023-06-30 16:49:14,227 [qtp1888567697-19] INFO  s.h.m.MatcherFilter - The requested route [/api/project/649f00f2d40a3d001f040ccf] has not been mapped in Spark for Accept: [*/*]
`
I tried with r5 on dev, master and i did access-control-allow-origin=*
in analysis.properties.

**Comment by javandres** [comment]
Hello @changtung what version of R5 are you using?

**Comment by changtung** [comment]
i've changed to 6.4 and its fine.
